### ISSUE TITLE
How to use the service?

### ISSUE THREAD

**Issue by anna-mo** [chainpoint/chainpoint-services#15] opened 2018-11-14 01:53 UTC
I'd run the make up command successfully, but the console went to the end and exit, is there some documents to guide developers use this service, this architeciture is pretty cool, thanks for your job!

**Comment by miketwenty1** [comment] 2018-11-14 01:57
Hey Anna, I'm unsure if you're having an issue. You might be just asking how to use the API of a node?
I'm guessing you have already looked at the README.
Feel free to look at the swagger docs.
https://app.swaggerhub.com/apis/chainpoint/node/1.0.0
We also have example code here:
https://github.com/chainpoint/chainpoint-client-js
https://runkit.com/tierion/chainpoint-client-js-example

Let me know if you're having any issues.

**Comment by grempe** [comment] 2018-11-14 06:37
@anna-mo This repository contains all of the code for the Chainpoint back-end infrastructure. This is likely not what you want.

I'd use the docs that @miketwenty1 provided above, or the main README for the chainpoint Node.

https://github.com/chainpoint/chainpoint-node/blob/develop/README.md

and 

https://chainpoint.org

Thanks for your interest. I'll close this issue as its not really related to `chainpoint-services` and is not a bug or feature request.

**Closed by grempe** 2018-11-14 06:37 UTC
